version: "3.8"

services:

  torrentmonitor:
    build: .

    container_name: torrentmonitor

    restart: unless-stopped

    environment:
      QB_URL: ${QB_URL}
      QB_USERNAME: ${QB_USERNAME}
      QB_PASSWORD: ${QB_PASSWORD}

      MONGO_URI: ${MONGO_URI}

      POLL_INTERVAL: ${POLL_INTERVAL}

      NODE_OPTIONS: --max-old-space-size=128

    dns:
      - 1.1.1.1
      - 1.0.0.1

    networks:
      - shared_network

    mem_limit: 256m
    mem_reservation: 128m

    cpus: 0.50

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  shared_network:
    external: true